#!/usr/bin/env python3
"""Prune a repository's history down to a few meaningful commits.

    prune_repo.py <repo> --mode releases      # one commit per published release (matched to PyPI sdists)
    prune_repo.py <repo> --mode last          # collapse everything into one commit
    prune_repo.py <repo> --mode keep --keep A B HEAD

Nothing is pushed without --yes; the default is a dry run that builds the new
history locally, proves it is content-identical, and prints what it would do.

Why not git-filter-repo: it rewrites commits one-for-one (paths, authors,
blobs). Collapsing a range to a single commit carrying that range's final tree
is a different operation, and `git commit-tree` over the existing tree objects
expresses it directly -- and makes the result verifiable, because the new tip
must point at the *same tree object* as the old tip.
"""
from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
import urllib.request
from datetime import datetime, timezone


def git(repo: str, *args: str, check: bool = True, input_bytes: bytes | None = None) -> str:
    p = subprocess.run(["git", "-C", repo, *args], capture_output=True,
                       input=input_bytes) if input_bytes is not None else \
        subprocess.run(["git", "-C", repo, *args], capture_output=True)
    out = p.stdout.decode()
    if check and p.returncode:
        sys.exit(f"git {' '.join(args)}\n{p.stderr.decode().strip()}")
    return out.strip()


def gh(*args: str, check: bool = True) -> str:
    p = subprocess.run(["gh", *args], capture_output=True, text=True)
    if check and p.returncode:
        return ""
    return p.stdout.strip()


def commit_time(repo: str, rev: str) -> datetime:
    return datetime.fromtimestamp(int(git(repo, "log", "-1", "--format=%ct", rev)), timezone.utc)


def pypi_releases(package: str) -> list[tuple[str, datetime]]:
    data = json.loads(fetch_url(f"https://pypi.org/pypi/{package}/json", 30))
    out = []
    for version, files in data["releases"].items():
        if not files:
            continue
        stamp = min(f["upload_time_iso_8601"] for f in files)
        out.append((version, datetime.fromisoformat(stamp.replace("Z", "+00:00"))))
    return sorted(out, key=lambda vt: vt[1])


def project_name(repo: str) -> str | None:
    try:
        text = git(repo, "show", "HEAD:pyproject.toml")
    except SystemExit:
        return None
    for line in text.splitlines():
        if line.startswith("name"):
            return line.split("=", 1)[1].strip().strip('"\'')
    return None


def version_in_tree(repo: str, rev: str) -> str | None:
    p = subprocess.run(["git", "-C", repo, "show", f"{rev}:pyproject.toml"],
                       capture_output=True, text=True)
    if p.returncode:
        return None
    for line in p.stdout.splitlines():
        if line.startswith("version"):
            return line.split("=", 1)[1].strip().strip('"\'')
    return None


CRLF, LF = chr(13).encode() + chr(10).encode(), chr(10).encode()
UA = {"User-Agent": "prune_repo/1.0"}


def fetch_url(url: str, timeout: int = 60) -> bytes:
    """crandb answers 403 to a request with no User-Agent."""
    return urllib.request.urlopen(
        urllib.request.Request(url, headers=UA), timeout=timeout).read()


def norm(data: bytes) -> bytes:
    """Normalise CRLF to LF before hashing.

    A source archive built on Windows stores CRLF while git stores LF, which
    makes every text file compare unequal for a reason that has nothing to do
    with which commit it came from. guess 0.1 matched 6/57 files raw and 57/57
    normalised.
    """
    return data.replace(CRLF, LF)


def cran_releases(package: str) -> list[tuple[str, datetime]]:
    timeline = json.loads(fetch_url(f"https://crandb.r-pkg.org/{package}/all", 30)).get("timeline", {})
    return sorted(((v, datetime.fromisoformat(t)) for v, t in timeline.items()),
                  key=lambda vt: vt[1])


def cran_tarball(package: str, version: str) -> dict[str, bytes] | None:
    import io, tarfile
    base = "https://cran.r-project.org/src/contrib"
    for url in (f"{base}/{package}_{version}.tar.gz",
                f"{base}/Archive/{package}/{package}_{version}.tar.gz"):
        try:
            blob = fetch_url(url)
            break
        except Exception:
            blob = None
    if blob is None:
        return None
    out = {}
    with tarfile.open(fileobj=io.BytesIO(blob)) as tf:
        for m in tf.getmembers():
            if not m.isfile():
                continue
            rel = m.name.split("/", 1)[1] if "/" in m.name else m.name
            # generated by R CMD build, never in git
            if rel in ("MD5", "data/datalist") or rel.startswith(("inst/doc/", "build/")):
                continue
            out[rel] = tf.extractfile(m).read()
    return out


def r_package(repo: str) -> str | None:
    p = subprocess.run(["git", "-C", repo, "show", "HEAD:DESCRIPTION"], capture_output=True)
    if p.returncode:
        return None
    for line in p.stdout.decode().splitlines():
        if line.startswith("Package:"):
            return line.split(":", 1)[1].strip()
    return None


def sdist_files(package: str, version: str) -> dict[str, bytes] | None:
    """Download the published sdist and return {path-relative-to-root: bytes}."""
    import io, tarfile
    urls = json.loads(fetch_url(f"https://pypi.org/pypi/{package}/{version}/json", 30))["urls"]
    tars = [u["url"] for u in urls if u["filename"].endswith(".tar.gz")]
    if not tars:
        return None
    blob = fetch_url(tars[0])
    out = {}
    with tarfile.open(fileobj=io.BytesIO(blob)) as tf:
        for member in tf.getmembers():
            if not member.isfile():
                continue
            rel = member.name.split("/", 1)[1] if "/" in member.name else member.name
            # PKG-INFO and *.egg-info are generated at build time, never in git
            if rel == "PKG-INFO" or ".egg-info/" in rel:
                continue
            data = tf.extractfile(member).read()
            # setuptools writes a stub setup.cfg into the sdist when the project
            # has none; incline 0.3.0 ships "[egg_info]\ntag_build =\ntag_date = 0"
            if rel == "setup.cfg" and b"[egg_info]" in data and b"install_requires" not in data:
                continue
            out[rel] = data
    # uv_build normalises pyproject.toml in the sdist and preserves the exact
    # source file as pyproject.toml.orig. Compare that original under its git
    # path; both the normalised file and the .orig name are build artefacts.
    if "pyproject.toml.orig" in out:
        out["pyproject.toml"] = out.pop("pyproject.toml.orig")
    return out


def find_release_commits(repo: str, branch: str) -> list[tuple[str, str]]:
    """Map each published version to the commit whose tree it was built from.

    By matching published archive contents against each commit's blobs, never by
    timestamps. Timestamps fail in both directions: a version bump can sit
    unreleased for days, and a manual upload from a working tree committed
    minutes later puts the release commit AFTER its own upload.

    Reads each commit's tree once (`ls-tree -r`) rather than asking per file --
    172 commits x 75 files is 12,900 subprocesses the naive way.
    """
    rpkg, pypkg = r_package(repo), project_name(repo)
    if rpkg:
        versions, fetch, kind = cran_releases(rpkg), lambda v: cran_tarball(rpkg, v), "CRAN"
    elif pypkg:
        versions, fetch, kind = pypi_releases(pypkg), lambda v: sdist_files(pypkg, v), "PyPI"
    else:
        sys.exit("no pyproject.toml or DESCRIPTION; use --mode keep")
    print(f"== matching {kind} archives against every commit")

    revs = git(repo, "rev-list", "--reverse", branch).splitlines()
    trees = {}
    for rev in revs:
        entry = {}
        for line in git(repo, "ls-tree", "-r", rev).splitlines():
            meta, path = line.split("\t", 1)
            entry[path] = meta.split()[2]
        trees[rev] = entry

    found = []
    for version, when in versions:
        files = fetch(version)
        if not files:
            print(f"  ! {version}: no source archive published; skipped")
            continue
        want = {}
        for rel, data in files.items():
            want[rel] = {git(repo, "hash-object", "--stdin", input_bytes=data),
                         git(repo, "hash-object", "--stdin", input_bytes=norm(data))}
        scored = [(sum(1 for k, hs in want.items() if trees[r].get(k) in hs), r) for r in revs]
        best = max(s for s, _ in scored)
        # Ties are common: any commit that touches only unpackaged files (docs, CI,
        # lockfiles) leaves the tree matching. A fully matching existing release
        # tag is the strongest evidence; otherwise take the tie closest in time to
        # the upload. "Newest tie" put stable-cart 1.1.0 five months after release.
        ties = [r for s, r in scored if s == best]
        tagged = []
        for name in (f"v{version}", version):
            target = git(repo, "rev-parse", "--verify", "--quiet",
                         f"refs/tags/{name}^{{commit}}", check=False)
            if target in ties:
                tagged.append(target)
        rev = tagged[0] if tagged else min(
            ties, key=lambda r: abs((commit_time(repo, r) - when).total_seconds())
        )
        subject = git(repo, "log", "-1", "--format=%s", rev)[:44]
        missed = [k for k, hs in want.items() if trees[rev].get(k) not in hs]
        # the build tool rewrites these two, so they never match
        real = [m for m in missed if m not in ("DESCRIPTION", "PKG-INFO")]
        if real:
            print(f"  ! {version} ({when:%Y-%m-%d}): best {rev[:7]} is {best}/{len(want)}; "
                  f"not tagging. Differs on: {', '.join(real[:6])}"
                  f"{' ...' if len(real) > 6 else ''}")
            continue
        print(f"  {version:<8} {when:%Y-%m-%d}  {rev[:7]}  {best}/{len(want)}  {subject}")
        found.append((version, rev))
    return found


# Machine-authored dependency bumps. Everything after the last matched release
# is kept commit by commit, which is right for unreleased work and wrong for
# these: the content survives in the tree either way, and a repo with months of
# Dependabot traffic since its last release keeps dozens of them. ethnicolr kept
# 25, because its newest release did not match a commit and the anchor fell back
# eight months.
#
# Matched by author first, since that is what actually identifies them. The
# subject patterns are a fallback for bumps merged under a human's name, and are
# deliberately narrow: "bump to 0.9.8" and "chore: ... and bump version" are
# release commits, so anything without a "from"/"group"/"requirement" object
# does not match.
BUMP_AUTHOR = re.compile(r"dependabot|renovate|pre-commit-ci", re.I)
BUMP_SUBJECT = re.compile(
    r"^(?:bump \S+ from |"
    r"bump the \S+ group|"
    r"bump \S+ in the \S+ group|"
    r"update \S+ requirement from )",
    re.I,
)


def is_bump(repo: str, rev: str) -> bool:
    if BUMP_AUTHOR.search(git(repo, "log", "-1", "--format=%an%n%ae", rev)):
        return True
    return bool(BUMP_SUBJECT.match(git(repo, "log", "-1", "--format=%s", rev)))


def build(repo: str, keeps: list[str], messages: dict[str, str]) -> str:
    parent = ""
    for rev in keeps:
        env_keys = {"GIT_AUTHOR_NAME": "%an", "GIT_AUTHOR_EMAIL": "%ae", "GIT_AUTHOR_DATE": "%aD",
                    "GIT_COMMITTER_NAME": "%cn", "GIT_COMMITTER_EMAIL": "%ce", "GIT_COMMITTER_DATE": "%cD"}
        env = {k: git(repo, "log", "-1", f"--format={v}", rev) for k, v in env_keys.items()}
        msg = messages.get(rev) or git(repo, "log", "-1", "--format=%B", rev)
        cmd = ["git", "-C", repo, "commit-tree", f"{rev}^{{tree}}"]
        if parent:
            cmd += ["-p", parent]
        p = subprocess.run(cmd, input=msg, capture_output=True, text=True,
                           env={**__import__("os").environ, **env})
        if p.returncode:
            sys.exit(p.stderr)
        parent = p.stdout.strip()
    return parent


def blocking_rulesets(slug: str) -> list[dict]:
    raw = gh("api", f"repos/{slug}/rulesets")
    out = []
    for entry in json.loads(raw or "[]"):
        detail = json.loads(gh("api", f"repos/{slug}/rulesets/{entry['id']}") or "{}")
        kinds = {r["type"] for r in detail.get("rules", [])}
        if detail.get("enforcement") == "active" and kinds & {
                "required_status_checks", "non_fast_forward", "pull_request"}:
            out.append(detail)
    return out


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("repo")
    ap.add_argument("--mode", choices=["releases", "last", "keep"], default="releases")
    ap.add_argument("--keep", nargs="*", default=[])
    ap.add_argument("--message-dir", help="dir of <short-sha>.txt commit messages")
    ap.add_argument("--keep-bumps", action="store_true",
                    help="keep Dependabot-style commits in the post-release tail")
    ap.add_argument("--tag", action="store_true", help="tag release commits (never creates Releases)")
    ap.add_argument("--yes", action="store_true", help="actually push")
    args = ap.parse_args()
    repo = args.repo

    if git(repo, "status", "--porcelain"):
        sys.exit("working tree dirty")
    git(repo, "fetch", "--prune", "-q")
    branch = git(repo, "symbolic-ref", "--short", "HEAD")
    slug = git(repo, "remote", "get-url", "origin").split("github.com")[-1].lstrip(":/").removesuffix(".git")
    head = git(repo, "rev-parse", "HEAD")
    head_tree = git(repo, "rev-parse", "HEAD^{tree}")
    old_n = int(git(repo, "rev-list", "--count", "HEAD"))
    print(f"== {slug} on {branch}: {old_n} commits")

    releases: list[tuple[str, str]] = []
    if args.mode == "releases":
        releases = find_release_commits(repo, branch)
        keeps = [rev for _, rev in releases]
        tail = git(repo, "rev-list", "--reverse", f"{keeps[-1]}..HEAD").splitlines() if keeps else []
        if not args.keep_bumps:
            bumps = [r for r in tail if is_bump(repo, r)]
            tail = [r for r in tail if r not in set(bumps)]
            if bumps:
                print(f"== dropped {len(bumps)} dependency-bump commit(s) from the tail")
        keeps += tail
    elif args.mode == "last":
        keeps = [head]
    else:
        keeps = [git(repo, "rev-parse", r) for r in args.keep]
    if not keeps:
        sys.exit("nothing to keep")
    if git(repo, "rev-parse", f"{keeps[-1]}^{{tree}}") != head_tree:
        keeps.append(head)

    messages: dict[str, str] = {}
    if args.message_dir:
        import pathlib
        for rev in keeps:
            f = pathlib.Path(args.message_dir) / f"{rev[:7]}.txt"
            if f.exists():
                messages[rev] = f.read_text()

    new = build(repo, keeps, messages)
    if git(repo, "rev-parse", f"{new}^{{tree}}") != head_tree:
        sys.exit("ABORT: new tip tree differs from old tip tree")
    if git(repo, "diff", head, new):
        sys.exit("ABORT: diff between old and new tip is non-empty")
    print(f"== tree identical: {head_tree}")
    print(f"== {old_n} commits -> {len(keeps)}")
    for line in git(repo, "log", "--format=  %h %ad %s", "--date=short", new).splitlines():
        print(line)

    blockers = blocking_rulesets(slug)
    for b in blockers:
        print(f"== ruleset blocks direct pushes: {b['name']} (id {b['id']})")
        print(f"   disable: gh api repos/{slug}/rulesets/{b['id']} | "
              f"jq '{{name,target,enforcement:\"disabled\",bypass_actors,conditions,rules}}' | "
              f"gh api -X PUT repos/{slug}/rulesets/{b['id']} --input -")
        print("   (re-run with enforcement:\"active\" afterwards)")

    if not args.yes:
        print("== dry run; nothing pushed. re-run with --yes")
        return

    # A backup BRANCH would be visible clutter on GitHub forever. A bundle is one
    # local file holding the same objects, and restores with a plain git fetch.
    # It goes to the temp dir, not ~/.claude/backups: a repo with data in it makes
    # a multi-GB bundle, and one left behind silently during a disk cleanup is
    # exactly the kind of file the user then has to hunt down. Delete it once a
    # fresh clone passes its tests.
    import pathlib
    import tempfile
    bdir = pathlib.Path(tempfile.gettempdir())
    bundle = bdir / f"{slug.split('/')[-1]}-pre-prune-{head[:7]}.bundle"
    git(repo, "branch", "-f", "_prune_backup", head)
    git(repo, "bundle", "create", str(bundle), "_prune_backup")
    git(repo, "branch", "-D", "_prune_backup")
    restored = git(repo, "bundle", "list-heads", str(bundle))
    if head[:7] not in restored:
        sys.exit(f"ABORT: bundle {bundle} does not contain {head[:7]}")
    print(f"== backup bundled: {bundle} ({bundle.stat().st_size / 2**20:.0f} MB) "
          "-- delete it once the rewritten head is verified")

    workflows = [w for w in gh("workflow", "list", "-R", slug, "--json", "name,state",
                               "--jq", '.[]|select(.state=="active")|.name').splitlines() if w]
    for w in workflows:
        gh("workflow", "disable", w, "-R", slug)
    print(f"== disabled {len(workflows)} workflows")
    try:
        git(repo, "update-ref", f"refs/heads/{branch}", new)
        print(git(repo, "push", "--force-with-lease", "origin", branch))
        if args.tag:
            for version, old_rev in releases:
                idx = keeps.index(old_rev)
                new_rev = git(repo, "rev-list", "--reverse", new).splitlines()[idx]
                git(repo, "tag", "-a", "-f", f"v{version}", new_rev, "-m", version)
            names = [f"v{v}" for v, _ in releases]
            if names:
                git(repo, "push", "--force", "origin", *names)
                print(f"== tagged {', '.join(names)} (no GitHub Releases: those fire "
                      "workflows from the tag's own tree)")
    finally:
        for w in workflows:
            gh("workflow", "enable", w, "-R", slug)
        print(f"== re-enabled {len(workflows)} workflows")
        if workflows:
            # Disabling them is what keeps a stale release workflow in an old
            # tagged tree from firing -- but it also means the push that just
            # landed triggered no CI. Silence here is not a pass.
            print("== NOTE: workflows were disabled during the push, so nothing ran "
                  "against the rewritten head. Verify it yourself (fresh clone + "
                  "test run), or push an empty commit to trigger CI.")
    print(f"== rollback: git fetch {bundle} _prune_backup && "
          f"git push --force origin FETCH_HEAD:{branch}")


if __name__ == "__main__":
    main()
