/**
 * An MCP server that serves this repo's skills to surfaces with no filesystem.
 *
 * Two audiences, one catalog:
 *
 *   - Clients that speak SEP-2640 get `skills/list` and `skills/get`, with the
 *     SHA-256 digests the spec requires for content verification.
 *   - Clients that do not — which today is all of them — get one ordinary tool
 *     per skill, plus `read_skill_file` for the supporting files. This shim is
 *     meant to be deleted once the extension lands in hosts.
 *
 * Everything is read from index.json, generated by scripts/build_index.py and
 * committed. A file that is not in the index cannot be served: that is what
 * keeps a crafted `skill://` URI from reaching .github/workflows or any other
 * part of the repo.
 */

const PROTOCOL_VERSIONS = ["2026-07-28", "2025-11-25", "2025-06-18", "2025-03-26"];
const SKILLS_EXTENSION = "io.modelcontextprotocol/skills";
const INDEX_TTL_SECONDS = 60;
const FILE_TTL_SECONDS = 300;

const MIME_TYPES = {
  md: "text/markdown",
  py: "text/x-python",
  R: "text/x-r",
  r: "text/x-r",
  yaml: "application/yaml",
  yml: "application/yaml",
  json: "application/json",
  txt: "text/plain",
};

const CORS_HEADERS = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Methods": "GET, POST, OPTIONS",
  "Access-Control-Allow-Headers": "content-type, mcp-protocol-version, mcp-session-id, authorization",
  "Access-Control-Expose-Headers": "mcp-protocol-version, mcp-session-id",
  "Access-Control-Max-Age": "86400",
};

const rawBase = (env) =>
  `https://raw.githubusercontent.com/${env.GITHUB_REPO}/${env.GITHUB_REF}`;

function mimeType(path) {
  const extension = path.split(".").pop();
  return MIME_TYPES[extension] ?? "text/plain";
}

function toolName(skillName) {
  return `skill_${skillName.replace(/-/g, "_")}`;
}

async function loadIndex(env) {
  const response = await fetch(`${rawBase(env)}/index.json`, {
    cf: { cacheTtl: INDEX_TTL_SECONDS, cacheEverything: true },
  });
  if (!response.ok) {
    throw new Error(`index.json unavailable (${response.status})`);
  }
  return response.json();
}

/** Map every indexed file to its skill:// URI, and back to a repo path. */
function buildRoutes(index) {
  const files = new Map();
  for (const skill of index.skills) {
    for (const file of skill.files) {
      files.set(`skill://${skill.name}/${file.path}`, {
        repoPath: `${skill.name}/${file.path}`,
        skill: skill.name,
        ...file,
      });
    }
  }
  return files;
}

async function readFile(env, repoPath) {
  const response = await fetch(`${rawBase(env)}/${repoPath}`, {
    cf: { cacheTtl: FILE_TTL_SECONDS, cacheEverything: true },
  });
  if (!response.ok) {
    throw new Error(`cannot read ${repoPath} (${response.status})`);
  }
  return response.text();
}

/**
 * The tool-shim payload: SKILL.md, then a manifest of what else this skill has.
 * Without the manifest a model reads the body, sees "see references/voice.md",
 * and has no way to ask for it — the shim would truncate the skill to its first
 * level and look like it worked.
 */
function supportingFilesNote(skill) {
  const others = skill.files.filter((file) => file.path !== "SKILL.md");
  if (others.length === 0) return "";
  const list = others
    .map((file) => `- skill://${skill.name}/${file.path}`)
    .join("\n");
  return (
    `\n\n---\n\nThis skill bundles ${others.length} supporting file` +
    `${others.length === 1 ? "" : "s"}. Read one with the \`read_skill_file\` ` +
    `tool when the instructions above reference it:\n\n${list}\n`
  );
}

function skillEntry(skill) {
  return {
    uri: `skill://${skill.name}/SKILL.md`,
    frontmatter: skill.frontmatter,
    resources: skill.files.map((file) => ({
      uri: `skill://${skill.name}/${file.path}`,
      digest: file.digest,
    })),
  };
}

const HANDLERS = {
  initialize(params) {
    const requested = params?.protocolVersion;
    return {
      protocolVersion: PROTOCOL_VERSIONS.includes(requested)
        ? requested
        : PROTOCOL_VERSIONS[0],
      capabilities: {
        tools: {},
        resources: {},
        experimental: { [SKILLS_EXTENSION]: {} },
      },
      serverInfo: { name: "gojiplus-skills", version: "1.0.0" },
      instructions:
        "Agent Skills for empirical, software, Cloudflare, writing, and release work. Each skill_* tool " +
        "returns a full skill: read it and follow it. Supporting files are " +
        "listed at the end of each skill and fetched with read_skill_file.",
    };
  },

  ping() {
    return {};
  },

  async "tools/list"(params, context) {
    const tools = context.index.skills.map((skill) => ({
      name: toolName(skill.name),
      description: skill.frontmatter.description,
      inputSchema: { type: "object", properties: {}, additionalProperties: false },
    }));

    tools.push({
      name: "read_skill_file",
      description:
        "Read a supporting file bundled with a skill — a reference, checklist, " +
        "or script listed at the end of that skill. Use only after loading the " +
        "skill itself.",
      inputSchema: {
        type: "object",
        properties: {
          uri: {
            type: "string",
            description: "A skill:// URI, e.g. skill://on-writing/references/voice.md",
          },
        },
        required: ["uri"],
        additionalProperties: false,
      },
    });

    return { tools };
  },

  async "tools/call"(params, context) {
    const { name, arguments: args } = params ?? {};

    if (name === "read_skill_file") {
      const uri = args?.uri;
      const file = context.routes.get(uri);
      if (!file) {
        // Not an error result: a wrong URI is a model mistake it can recover
        // from, and isError lets it see the correction.
        return {
          isError: true,
          content: [
            {
              type: "text",
              text: `No such file: ${uri}. Load the skill first; its supporting files are listed at the end.`,
            },
          ],
        };
      }
      const text = await readFile(context.env, file.repoPath);
      return { content: [{ type: "text", text }] };
    }

    const skill = context.index.skills.find(
      (candidate) => toolName(candidate.name) === name,
    );
    if (!skill) {
      throw { code: -32602, message: `Unknown tool: ${name}` };
    }

    const body = await readFile(context.env, `${skill.name}/SKILL.md`);
    return { content: [{ type: "text", text: body + supportingFilesNote(skill) }] };
  },

  async "resources/list"(params, context) {
    const resources = [];
    for (const skill of context.index.skills) {
      for (const file of skill.files) {
        const isEntry = file.path === "SKILL.md";
        resources.push({
          uri: `skill://${skill.name}/${file.path}`,
          name: isEntry ? skill.frontmatter.name : `${skill.name}/${file.path}`,
          description: isEntry ? skill.frontmatter.description : undefined,
          mimeType: mimeType(file.path),
        });
      }
    }
    return { resources };
  },

  async "resources/read"(params, context) {
    const uri = params?.uri;
    const file = context.routes.get(uri);
    if (!file) {
      throw { code: -32602, message: `Unknown resource: ${uri}` };
    }
    const text = await readFile(context.env, file.repoPath);
    return { contents: [{ uri, mimeType: mimeType(file.path), text }] };
  },

  // SEP-2640. No client ships this yet; it is here so that when one does, this
  // server is already correct rather than needing a rewrite.
  async "skills/list"(params, context) {
    return { skills: context.index.skills.map(skillEntry) };
  },

  async "skills/get"(params, context) {
    const uri = params?.uri;
    const skill = context.index.skills.find(
      (candidate) => `skill://${candidate.name}/SKILL.md` === uri,
    );
    if (!skill) {
      throw { code: -32602, message: `Unknown skill: ${uri}` };
    }
    return { skill: skillEntry(skill) };
  },
};

async function dispatch(message, context) {
  const { id, method, params } = message;

  // Notifications carry no id and expect no reply.
  if (id === undefined || id === null) return null;

  const handler = HANDLERS[method];
  if (!handler) {
    return {
      jsonrpc: "2.0",
      id,
      error: { code: -32601, message: `Method not found: ${method}` },
    };
  }

  try {
    return { jsonrpc: "2.0", id, result: await handler(params, context) };
  } catch (error) {
    const code = typeof error?.code === "number" ? error.code : -32603;
    return {
      jsonrpc: "2.0",
      id,
      error: { code, message: error?.message ?? "Internal error" },
    };
  }
}

const LANDING = `gojiplus/skills — MCP endpoint

POST JSON-RPC to this URL. Add it as a custom connector:
  Claude      Customize, then Connectors, then Add custom connector
  ChatGPT     Settings, Security and login, Developer mode; then ChatGPT Plugins

Use this endpoint with /mcp in connector settings.

Source: https://github.com/gojiplus/skills
`;

export default {
  async fetch(request, env) {
    if (request.method === "OPTIONS") {
      return new Response(null, { status: 204, headers: CORS_HEADERS });
    }

    if (request.method === "GET") {
      const url = new URL(request.url);
      if (url.pathname === "/health") {
        try {
          const index = await loadIndex(env);
          return Response.json(
            { ok: true, skills: index.skills.length },
            { headers: CORS_HEADERS },
          );
        } catch (error) {
          return Response.json(
            { ok: false, error: error.message },
            { status: 503, headers: CORS_HEADERS },
          );
        }
      }
      // No SSE stream: every response here fits in one JSON body, and
      // Streamable HTTP permits declining GET.
      return new Response(LANDING, {
        status: url.pathname === "/" ? 200 : 405,
        headers: { ...CORS_HEADERS, "content-type": "text/plain; charset=utf-8" },
      });
    }

    if (request.method !== "POST") {
      return new Response("Method not allowed", { status: 405, headers: CORS_HEADERS });
    }

    let payload;
    try {
      payload = await request.json();
    } catch {
      return Response.json(
        { jsonrpc: "2.0", id: null, error: { code: -32700, message: "Parse error" } },
        { status: 400, headers: CORS_HEADERS },
      );
    }

    let context;
    try {
      const index = await loadIndex(env);
      context = { env, index, routes: buildRoutes(index) };
    } catch (error) {
      return Response.json(
        { jsonrpc: "2.0", id: payload?.id ?? null, error: { code: -32603, message: error.message } },
        { status: 503, headers: CORS_HEADERS },
      );
    }

    const batch = Array.isArray(payload) ? payload : [payload];
    const responses = (await Promise.all(batch.map((m) => dispatch(m, context)))).filter(
      Boolean,
    );

    if (responses.length === 0) {
      return new Response(null, { status: 202, headers: CORS_HEADERS });
    }

    return Response.json(Array.isArray(payload) ? responses : responses[0], {
      headers: CORS_HEADERS,
    });
  },
};
